### ISSUE TITLE
urllib.parse doesn't work in python3

### ISSUE THREAD

**Issue by sourabhtk37** [inglesp/http-crawler#7]
The following import statement doesn't work in python3.

```
from urllib.parse import parse
```

We can replace the code with:

```
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
```

for both python2 and python3 compatibility.  What say? @inglesp

**Comment by inglesp** [comment]
Hi @sourabhtk37.  Thanks for taking a look at the code!  I'm a bit puzzled by this issue though, since (1) `from urllib.parse import parse` doesn't appear anywhere in the code, and (2) it doesn't work in Python 2 either!

Did you instead mean that there's a problem with `from urllib.parse import urljoin, urlparse` in Python 2?  If so, this is expected!

The code is tested under Python 3, but I know that it doesn't work with Python 2.  (See #1.)  If you'd like to tackle #1, I've added some notes about how I'd go about making the code work with Python 2.

**Comment by sourabhtk37** [comment]
It was there in src/http_crawler/**init**.py
I was having the error but now it's working fine.
Closing this issue.
